[package]
name = "cpc"
version = "1.6.0"
description = "evaluates math expressions, with support for units and conversion between units"
authors = ["Kasper Henningsen"]
edition = "2018"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/probablykasper/cpc#readme"
repository = "https://github.com/probablykasper/cpc"
documentation = "https://docs.rs/cpc"
keywords = ["math", "expression", "evaluate", "units", "convert"]
categories = ["mathematics", "science", "parsing", "text-processing", "value-formatting"]

[dependencies]
decimal = "2.1.0"
unicode-segmentation = "1.8.0"

[dev-dependencies]
regex = "1.5.4"
